- docker/deploy.sh
Adds a configurable artifact limit when setting up polyswarmd configuration in consul
Per polyswarm/polyswarmd#151
> Add artifact_limit to consul

- src/contractor/consul.py
- src/contractor/steps/ERC20Relay.py
- src/contractor/steps/NectarToken.py
> Push configs using kv api to prevent breakage, persistent relay address

- requirements.txt
- src/contractor/__main__.py
- src/contractor/deployer.py
- src/contractor/network.py
- src/contractor/watch.py
- tox.ini
Adding block logger I'm using for local debugging/testing, watching user account balance changes and contract function calls. related to https://github.com/polyswarm/development-private/issues/118.
> add block watcher for debugging

- docker/Dockerfile
- docker/config.jq
- docker/deploy.sh
Change config to enable profiler
> Change config templating

- src/contractor/network.py
Think this should handle it, more or less. Probably less.
> Handle ValueError in known transaction case

- requirements.txt
- src/contractor/__main__.py
- src/contractor/network.py
Sample functionality:
```
contractor repl --config config.yml --community gamma --network sidechain --chain side -a orchestration/contractor -i orchestration/contractor/sidechain.json --keyfile keyfile --password password
INFO:contractor.network:Connected to ethereum client at http://localhost:7545, network id: 1338
INFO:contractor.network:Using address: 0x34E583cf9C1789c3141538EeC77D9F0B8F7E89f2
INFO:contractor.network:Waiting for blocks to advance
INFO:contractor.network:Waiting for blocks to advance
INFO:contractor.network:Waiting for blocks to advance
INFO:contractor.network:Waiting for blocks to advance
INFO:contractor.network:Waiting for blocks to advance
Waiting for deployment results
INFO:contractor.network:Settled on transaction count 11
WARNING:contractor.deployer:homechain.json …
```
> Implement repl

- requirements.txt
I still have to run tests under Linux. Don't merge.
> Update PyYaml & SQLAlchemy to 'safe' versions

- contracts/BountyRegistry.sol
- docker/deploy.sh
Used wrong branch name in #48 
This is the correct one to match polyswarmd and client.
> Add artifact type to contracts. 

- tests/test_BountyRegistry.py
Fix tests after adding artifact type.
> Update tests with artifact_type

- .gitlab-ci.yml
I dont think the tox test is doing anything relevant to contractor.  Leaving it as is for now.
> CI formatting cleanup

- .gitlab-ci.yml
Fixing syntax error in `.gitlab-ci.yaml`
> using curl triggering because gitlab sintax was not working

- .gitlab-ci.yml
> use polyswarmd tag

- .gitlab-ci.yml
Building images in a special tag that is manually managed.
> adding manual image tagging

- .gitlab-ci.yml
Fix ci variable that was preventing releases to run in master branch.
> run release in master

- contracts/BountyRegistry.sol
Reduce size of BountyRegistry to fit back into rinkeby gas block limits
> Fit BountyRegistry on rinkeby, but only contract changes

- contracts/BountyRegistry.sol
- contracts/ERC20Relay.sol
- contracts/NectarToken.sol
- docker/deprecate.sh
- src/contractor/__main__.py
- src/contractor/exceptions.py
- src/contractor/network.py
- src/contractor/steps/BountyRegistry.py
- src/contractor/steps/ERC20Relay.py
- src/contractor/steps/NectarToken.py
- src/contractor/steps/__init__.py
- tests/test_BountyRegistry.py
- tests/test_ERC20Relay.py
- tests/test_NectarToken.py
Allows us to close down a community sidechain and automatically withdraw all NCT forcefully to the same wallet on homechain via relay.
> Add command to deactivate a community sidechain with cleanup

- contracts/ERC20Relay.sol
- tests/test_ERC20Relay.py
Fix transfer reverts when the remainder is less than fees
> Fix final remainder withdrawal for ERC20 Flush 

- examples/example_config.yml
- src/contractor/steps/ERC20Relay.py
Allow fee-manager address setup on start
> Add optional fee-manager in configuration

- contracts/BountyRegistry.sol
- tests/test_BountyRegistry.py
> Add fetching bountyGuids in pages

- docker/deploy.sh
With 15 second block times, this is an hour long wait. Skip that.
> Don't deprecate home BountyRegistry
